production:
  adapter: mysql
  database: rfid
  username: rfid
  password: dogthehoginaBog
  host: kleetus.xen.prgmr.com
development:
  adapter: mysql
  database: rfid_dev
  username: rfid
  password: dogthehoginaBog
  host: kleetus.xen.prgmr.com